name: Artifact

on: [push]

env:
  ARTIFACT_NAME: myartifact

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: check out the code
        run: actions/checkout@v2
      - name: Upload the artifact
        run: actions/upload-artifact@v2
        with:
          name: $(( env.ARTIFACT_NAME ))
          path: . 
